#Spring configuration
spring:
  application:
    name: prices
  # Sql initialization configuration
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#Server configuration
Server:
    port: 8001
# Health check configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
  # Actuator Info configuration
  info:
    env:
      enabled: true
# Info configuration
info:
  app:
    environment: production
# OpenAPI  configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/prices-api.yaml
